Update Readme
needed to fix instructions, otherwise it throws 
```
Error: unable to resolve a plugin from source: glamorous-to-emotion
    at PluginLoader.<anonymous> (/Users/danielberndt/.npm/_npx/24575/lib/node_modules/babel-codemod/src/PluginLoader.ts:14:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/danielberndt/.npm/_npx/24575/lib/node_modules/babel-codemod/src/PluginLoader.js:4:58)
    at <anonymous>
```